In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.request import urlopen
import re
import csv

# Getting EV prices information from website

In [7]:
url = "https://insideevs.com/news/565883/electric-car-prices-us/"

In [8]:
res = requests.get(url)
soup = BeautifulSoup(res.content, "html.parser")

In [9]:
tbody = soup.find('tbody')

In [10]:
rows = tbody.find_all('tr')

In [11]:
all_rows = []

for row in tbody.find_all('tr'):
    cols = row.find_all('td')
    cols_text = [ele.text.strip() for ele in cols]
    all_rows.append(cols_text)

In [12]:
headers = all_rows[0]
data_rows = all_rows[1:]

In [13]:
ev_prices_scraping = pd.DataFrame(data_rows, columns=headers)
ev_prices_scraping.head()

,Model,Base Price,Dest. Charge,Tax Credit,Effective Price
0,2023 Audi e-tron GT quattro 20-inch,"$104,900","+$1,495",N/A,"$106,395"
1,2023 Audi RS e-tron GT quattro 20-inch,"$143,900","+$1,495",N/A,"$145,395"
2,2024 Audi Q8 e-tron 20-inch,"$74,400","+$1,195",N/A,"$75,595"
3,2024 Audi Q8 e-tron Sportback (Ultra pack) 19-...,"$77,800","+$1,195",N/A,"$78,995"
4,2024 Audi Q8 e-tron Sportback 20-inch,"$77,800","+$1,195",N/A,"$78,995"

In [14]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\insideevs_ev_prices_scraping.csv'
ev_prices_scraping.to_csv(csv_file_path, index=False)

# Getting EV countries Sales, market, and usage share 2022 
###### Light-duty plug-in electric vehicle stock, market penetration, annual sales, and market share in the top selling countries and regional markets for latest available year

In [15]:
url2 = "https://en.wikipedia.org/wiki/Electric_car_use_by_country"
ev_sales22 = pd.read_html(url2)[2]
ev_sales22.head()

,Country or region,PEV stock/ cumulative sales (2022)[i],Annual sales (2022),Market share (2022),% of cars in use (2022)[ii]
0,China[iii],"14,100,000[71]","5,924,421[72]",30.0%[72],4.9%[71]
1,Europe[iv],"7,800,000[71]","2,602,431[73]",23.0%[73],2.4%[71]
2,United States[iii],"2,960,000[71]","990,000[71]",7.7%[71],1.3%[71]
3,Germany[iii],"1,877,721[74]","832,652[75]",31.4%[75],3.85%[74]
4,California[iii],"1,385,383[76]","343,244[76]",18.7%[76],3.85% (2021)[77]

In [16]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\wikipedia_ev_sales22_scraping.csv'
ev_sales22.to_csv(csv_file_path, index=False)

# Ev sales per country 2027-2021
###### Light-duty plug-in electric vehicle yearly new sales and end-of-year cumulative sales (or stock) in the top PEV selling countries and regional markets

In [17]:
url3 = "https://en.wikipedia.org/wiki/Electric_car_use_by_country"
ev_sales = pd.read_html(url3)[3]
ev_sales.head()

            Country                 2021                              2020  \
            Country                stock           sales             stock
0      China[i][ii]   7,842,668 [87][88]  3,334,000 [87]    4,508,668 [88]
1  United States[i]       2,322,291 [16]    607,567 [16]    1,741,566 [94]
2        Germany[i]  ≈1,380,000 [18][19]    681,410 [19]     ≈700,000 [18]
3            France        786,274 [103]   315,978 [103]     470,295 [104]
4    United Kingdom       ≈745,000 [109]   305,281 [110]  434,282 [1][111]

                                          2019                  \
            sales                        stock           sales
0  1,246,000 [89]                3,349,100 [1]  1,204,000 [90]
1    297,939 [94]                1,450,020 [1]    329,528 [95]
2    394,632 [99]  305,589 [32][100][101][102]   108,839 [102]
3   194,881 [104]                275,575 [104]    69,466 [105]
4   175,082 [111]                  259,200 [1]    72,584 [112]

                          2018                                       2017  \
                         stock              sales                   stock
0           2,243,772 [91][92]  1,016,002 [92][i]          1,227,770 [91]
1               1,126,000 [96]       361,307 [96]        764,666 [97][98]
2       196,750 [32][100][101]       67,504 [101]       129,246 [32][100]
3  204,617 [52][106][107][108]       53,745 [108]  149,797 [52][106][107]
4                197,000 [113]    59,911 [i][114]            137,000[113]


             sales
0  579,000 [93][i]
1     199,818 [96]
2     54,492 [100]
3     42,799 [108]
4  49,182 [i][114]

In [18]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\wikipedia_ev_sales_scraping.csv'
ev_sales.to_csv(csv_file_path, index=False)

# Scraping updated prices

In [19]:
url = "https://ev-database.org/#sort:path~type~order=.rank~number~desc|range-slider-range:prev~next=0~1200|range-slider-acceleration:prev~next=2~23|range-slider-topspeed:prev~next=110~350|range-slider-battery:prev~next=10~200|range-slider-towweight:prev~next=0~2500|range-slider-fastcharge:prev~next=0~1500|paging:currentPage=0|paging:number=all"

In [20]:
res = requests.get(url)
soup = BeautifulSoup(res.content, "html.parser")

In [21]:
ev_prices2 = []

ev_elements = soup.find_all('div', class_='list-item')

In [49]:
def extract_car_data(ev_elements):
    cars_list = []

    for wrapper in ev_elements:
        
        car_brand_element = wrapper.find('span', class_=True)
        car_brand = car_brand_element.get('class')[0] if car_brand_element else 'Brand not found'
        
        car_model_element = wrapper.find('span', class_='model')
        car_model = car_model_element.get_text(strip=True) if car_model_element else 'Model not found'
        
        price_de_element = wrapper.find('span', class_='country_de')
        price_de = price_de_element.get_text(strip=True) if price_de_element else 'DE Price not found'

        price_uk_element = wrapper.find('span', class_='country_uk')
        price_uk = price_uk_element.get_text(strip=True) if price_uk_element else 'UK Price not found'

        price_nl_element = wrapper.find('span', class_='country_nl')  
        price_nl = price_nl_element.get_text(strip=True) if price_nl_element else 'NL Price not found'

        car_acceleration_element = wrapper.find('span', class_='acceleration')  
        car_acceleration = car_acceleration_element.get_text(strip=True) if car_acceleration_element else 'Acceleration not found'

        car_top_speed_element = wrapper.find('span', class_='topspeed')  
        car_top_speed = car_top_speed_element.get_text(strip=True) if car_top_speed_element else 'Top speed not found'

        car_range_element = wrapper.find('span', class_='erange_real')  
        car_range = car_range_element.get_text(strip=True) if car_range_element else 'Range not found'

        car_efficiency_element = wrapper.find('span', class_='efficiency')  
        car_efficiency = car_efficiency_element.get_text(strip=True) if car_efficiency_element else 'Efficiency not found'

        car_fastcharge_element = wrapper.find('span', class_='fastcharge_speed_print')  
        car_fastcharge = car_fastcharge_element.get_text(strip=True) if car_fastcharge_element else 'Fastcharge not found'
        
        car_towing_capacity_element = wrapper.find('span', class_='towweight')  
        car_towing_capacity = car_towing_capacity_element.get_text(strip=True) if car_towing_capacity_element else 'Towing capacity not found' 
        
        car_battery_element = wrapper.find('span', class_='battery')
        car_battery = car_battery_element.get_text(strip=True) if car_battery_element else 'Useability Battery not found'
        
        car_v2_load_element = wrapper.find('span', title='Vehicle-2-Load Bi-directional charging possible')
        car_v2_load = car_v2_load_element.get_text(strip=True) if car_v2_load_element else 'No'
        
        car_v2_home_element = wrapper.find('span', title = 'Vehicle-2-Home Bi-directional charging possible')
        car_v2_home = car_v2_home_element.get_text(strip=True) if car_v2_home_element else 'No'
        
        car_v2_grid_element = wrapper.find('span', title = 'Vehicle-2-Grid Bi-directional charging possible')
        car_v2_grid = car_v2_grid_element.get_text(strip=True) if car_v2_grid_element else 'No'
            
        car_availability_element = wrapper.find('span', class_='current')  
        car_availability = car_availability_element.get_text(strip=True) if car_availability_element else 'Availability not found' 

        car_data = {
            'brand': car_brand,
            'model': car_model,
            'de_price': price_de,
            'uk_price': price_uk,
            'nl_price': price_nl,
            'acceleration_0-100km/h': car_acceleration,
            'top_speed': car_top_speed,
            'range': car_range,
            'efficiency': car_efficiency,
            'fastcharge': car_fastcharge,
            'towing_capacity(kg)': car_towing_capacity,
            'useable_battery': car_battery,
            'v2l' : car_v2_load,
            'v2h' : car_v2_home,
            'v2g' : car_v2_grid,
            'availability': car_availability
        }
        cars_list.append(car_data)

    return cars_list

def print_compact_car_data(cars_list):
    for car in cars_list:
        print(f"Name: {car['name']}, DE Price: {car['de_price']}, Range: {car['range']}")

In [50]:
cars_list = extract_car_data(ev_elements)
data_wrappers = pd.DataFrame(cars_list)
data_wrappers

,brand,model,de_price,uk_price,nl_price,acceleration_0-100km/h,top_speed,range,efficiency,fastcharge,towing_capacity(kg),useable_battery,v2l,v2h,v2g,availability
0,tesla,Model Y Long Range Dual Motor,"€59,017","£52,990","€54,993",5.0 sec,217 km/h,435 km,172 Wh/km,670 km/h,1600,75,No,No,No,Available to order since February 2022
1,byd,ATTO 3,"€44,625","£37,195","€42,998",7.3 sec,160 km/h,330 km,183 Wh/km,370 km/h,,60.5,L,No,No,Available to order since August 2022
2,tesla,Model 3,"€46,220","£39,990","€43,993",6.1 sec,201 km/h,420 km,137 Wh/km,700 km/h,1000,57.5,No,No,No,Available to order since September 2023
3,tesla,Model 3 Long Range Dual Motor,"€55,220","£49,990","€51,993",4.4 sec,201 km/h,505 km,149 Wh/km,780 km/h,1000,75,No,No,No,Available to order since September 2023
4,mg,MG4 Electric 64 kWh,"€39,990","£29,495","€35,785",7.9 sec,160 km/h,360 km,171 Wh/km,630 km/h,500,61.7,L,No,No,Available to order since October 2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,peugeot,e-Traveller Long 50 kWh,"€54,430","£43,625","€59,364",13.1 sec,130 km/h,185 km,250 Wh/km,290 km/h,1000,46.3,No,No,No,Available to order since November 2020
354,citroen,e-SpaceTourer XL 50 kWh,"€54,430","£37,885","€59,019",12.1 sec,130 km/h,180 km,257 Wh/km,290 km/h,1000,46.3,No,No,No,Available to order since November 2020
355,opel,Vivaro-e Combi L 75 kWh,"€57,775",N/A,"€59,059",13.3 sec,130 km/h,260 km,262 Wh/km,280 km/h,1000,68,No,No,No,Available to order since October 2020
356,fiat,E-Ulysse L2 50 kWh,"€55,990",N/A,N/A,12.1 sec,130 km/h,185 km,250 Wh/km,290 km/h,1000,46.3,No,No,No,Available to order since June 2022
357,mercedes,EQV 250 Extra-Long,"€68,949",N/A,N/A,12.0 sec,160 km/h,210 km,286 Wh/km,200 km/h,,60,No,No,No,Available to order since October 2021

In [51]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\ev-database_prices23_scraping.csv'
data_wrappers.to_csv(csv_file_path, index=False)