In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.request import urlopen
import re
import csv

# Getting EV prices information from website

In [3]:
url = "https://insideevs.com/news/565883/electric-car-prices-us/"

In [4]:
res = requests.get(url)
soup = BeautifulSoup(res.content, "html.parser")

In [5]:
tbody = soup.find('tbody')

In [6]:
rows = tbody.find_all('tr')

In [7]:
all_rows = []

for row in tbody.find_all('tr'):
    cols = row.find_all('td')
    cols_text = [ele.text.strip() for ele in cols]
    all_rows.append(cols_text)

In [8]:
headers = all_rows[0]
data_rows = all_rows[1:]

In [9]:
ev_prices_scraping = pd.DataFrame(data_rows, columns=headers)
ev_prices_scraping

,Model,Base Price,Dest. Charge,Tax Credit,Effective Price
0,2023 Audi e-tron GT quattro 20-inch,"$104,900","+$1,495",N/A,"$106,395"
1,2023 Audi RS e-tron GT quattro 20-inch,"$143,900","+$1,495",N/A,"$145,395"
2,2024 Audi Q8 e-tron 20-inch,"$74,400","+$1,195",N/A,"$75,595"
3,2024 Audi Q8 e-tron Sportback (Ultra pack) 19-...,"$77,800","+$1,195",N/A,"$78,995"
4,2024 Audi Q8 e-tron Sportback 20-inch,"$77,800","+$1,195",N/A,"$78,995"
...,...,...,...,...,...
212,2023 Volvo XC40 Recharge 19-inch,"$53,550","+$1,095",N/A,"$54,645"
213,2024 Volvo C40 Recharge RWD 19-inch,,,N/A,
214,2024 Volvo C40 Recharge AWD 19-inch,,,N/A,
215,2024 Volvo XC40 Recharge RWD 19-inch,,,N/A,
216,2024 Volvo XC40 Recharge AWD 19-inch,,,N/A,

In [10]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\insideevs_ev_prices_scraping.csv'
ev_prices_scraping.to_csv(csv_file_path, index=False)

# Getting EV countries Sales, market, and usage share 2022 
###### Light-duty plug-in electric vehicle stock, market penetration, annual sales, and market share in the top selling countries and regional markets for latest available year

In [11]:
url2 = "https://en.wikipedia.org/wiki/Electric_car_use_by_country"
ev_sales22 = pd.read_html(url2)[2]
ev_sales22.head()

,Country or region,PEV stock/ cumulative sales (2022)[i],Annual sales (2022),Market share (2022),% of cars in use (2022)[ii]
0,China[iii],"14,100,000[71]","5,924,421[72]",30.0%[72],4.9%[71]
1,Europe[iv],"7,800,000[71]","2,602,431[73]",23.0%[73],2.4%[71]
2,United States[iii],"2,960,000[71]","990,000[71]",7.7%[71],1.3%[71]
3,Germany[iii],"1,877,721[74]","832,652[75]",31.4%[75],3.85%[74]
4,California[iii],"1,385,383[76]","343,244[76]",18.7%[76],3.85% (2021)[77]

In [12]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\wikipedia_ev_sales22_scraping.csv'
ev_sales22.to_csv(csv_file_path, index=False)

# Ev sales per country 2027-2021
###### Light-duty plug-in electric vehicle yearly new sales and end-of-year cumulative sales (or stock) in the top PEV selling countries and regional markets

In [15]:
url3 = "https://en.wikipedia.org/wiki/Electric_car_use_by_country"
ev_sales = pd.read_html(url3)[3]
ev_sales.head()

            Country                 2021                              2020  \
            Country                stock           sales             stock
0      China[i][ii]   7,842,668 [87][88]  3,334,000 [87]    4,508,668 [88]
1  United States[i]       2,322,291 [16]    607,567 [16]    1,741,566 [94]
2        Germany[i]  â‰ˆ1,380,000 [18][19]    681,410 [19]     â‰ˆ700,000 [18]
3            France        786,274 [103]   315,978 [103]     470,295 [104]
4    United Kingdom       â‰ˆ745,000 [109]   305,281 [110]  434,282 [1][111]

                                          2019                  \
            sales                        stock           sales
0  1,246,000 [89]                3,349,100 [1]  1,204,000 [90]
1    297,939 [94]                1,450,020 [1]    329,528 [95]
2    394,632 [99]  305,589 [32][100][101][102]   108,839 [102]
3   194,881 [104]                275,575 [104]    69,466 [105]
4   175,082 [111]                  259,200 [1]    72,584 [112]

                          2018                                       2017  \
                         stock              sales                   stock
0           2,243,772 [91][92]  1,016,002 [92][i]          1,227,770 [91]
1               1,126,000 [96]       361,307 [96]        764,666 [97][98]
2       196,750 [32][100][101]       67,504 [101]       129,246 [32][100]
3  204,617 [52][106][107][108]       53,745 [108]  149,797 [52][106][107]
4                197,000 [113]    59,911 [i][114]            137,000[113]


             sales
0  579,000 [93][i]
1     199,818 [96]
2     54,492 [100]
3     42,799 [108]
4  49,182 [i][114]

In [16]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\wikipedia_ev_sales_scraping.csv'
ev_sales.to_csv(csv_file_path, index=False)

# Scraping updated prices

In [25]:
url = "https://ev-database.org/#sort:path~type~order=.rank~number~desc|range-slider-range:prev~next=0~1200|range-slider-acceleration:prev~next=2~23|range-slider-topspeed:prev~next=110~350|range-slider-battery:prev~next=10~200|range-slider-towweight:prev~next=0~2500|range-slider-fastcharge:prev~next=0~1500|paging:currentPage=0|paging:number=all"

In [26]:
res = requests.get(url)
soup = BeautifulSoup(res.content, "html.parser")

In [27]:
ev_prices2 = []

ev_elements = soup.find_all('div', class_='list-item')

In [37]:
def extract_car_data(ev_elements):
    cars_list = []

    for wrapper in ev_elements:
        car_name_element = wrapper.find('h2')
        car_name = car_name_element.get_text(strip=True) if car_name_element else 'Name not found'

        price_de_element = wrapper.find('span', class_='country_de')
        price_de = price_de_element.get_text(strip=True) if price_de_element else 'DE Price not found'

        price_uk_element = wrapper.find('span', class_='country_uk')
        price_uk = price_uk_element.get_text(strip=True) if price_uk_element else 'UK Price not found'

        price_nl_element = wrapper.find('span', class_='country_nl')  
        price_nl = price_nl_element.get_text(strip=True) if price_nl_element else 'NL Price not found'

        car_acceleration_element = wrapper.find('span', class_='acceleration')  
        car_acceleration = car_acceleration_element.get_text(strip=True) if car_acceleration_element else 'Acceleration not found'

        car_top_speed_element = wrapper.find('span', class_='topspeed')  
        car_top_speed = car_top_speed_element.get_text(strip=True) if car_top_speed_element else 'Top speed not found'

        car_range_element = wrapper.find('span', class_='erange_real')  
        car_range = car_range_element.get_text(strip=True) if car_range_element else 'Range not found'

        car_efficiency_element = wrapper.find('span', class_='efficiency')  
        car_efficiency = car_efficiency_element.get_text(strip=True) if car_efficiency_element else 'Efficiency not found'

        car_fastcharge_element = wrapper.find('span', class_='fastcharge_speed_print')  
        car_fastcharge = car_fastcharge_element.get_text(strip=True) if car_fastcharge_element else 'Fastcharge not found'
        
        car_towing_capacity_element = wrapper.find('span', class_='towweight')  
        car_towing_capacity = car_towing_capacity_element.get_text(strip=True) if car_towing_capacity_element else 'Towing capacity not found' 
        
        car_availability_element = wrapper.find('span', class_='current')  
        car_availability = car_availability_element.get_text(strip=True) if car_availability_element else 'Availability not found' 

        car_data = {
            'name': car_name,
            'de_price': price_de,
            'uk_price': price_uk,
            'nl_price': price_nl,
            'acceleration_0-100km/h': car_acceleration,
            'top_speed': car_top_speed,
            'range': car_range,
            'efficiency': car_efficiency,
            'fastcharge': car_fastcharge,
            'towing_capacity(kg)': car_towing_capacity,
            'availability': car_availability
        }
        cars_list.append(car_data)

    return cars_list

def print_compact_car_data(cars_list):
    for car in cars_list:
        print(f"Name: {car['name']}, DE Price: {car['de_price']}, Range: {car['range']}")

In [38]:
cars_list = extract_car_data(ev_elements)
print_compact_car_data(cars_list)

Name: TeslaModel Y Long Range Dual Motor, DE Price: â‚¬59,017, Range: 435 km
Name: BYDATTO 3, DE Price: â‚¬44,625, Range: 330 km
Name: TeslaModel 3, DE Price: â‚¬46,220, Range: 420 km
Name: TeslaModel 3 Long Range Dual Motor, DE Price: â‚¬55,220, Range: 505 km
Name: TeslaModel Y, DE Price: â‚¬47,567, Range: 350 km
Name: MGMG4 Electric 64 kWh, DE Price: â‚¬39,990, Range: 360 km
Name: BYDSEAL 82.5 kWh AWD Excellence, DE Price: â‚¬53,668, Range: 485 km
Name: BMWiX xDrive40, DE Price: â‚¬77,300, Range: 360 km
Name: BMWi4 eDrive40, DE Price: â‚¬59,200, Range: 515 km
Name: Citroene-C3, DE Price: â‚¬23,300, Range: 250 km
Name: BMWiX1 xDrive30, DE Price: â‚¬55,000, Range: 380 km
Name: KiaNiro EV, DE Price: â‚¬45,690, Range: 385 km
Name: HyundaiKona Electric 64 kWh, DE Price: â‚¬42,900, Range: 390 km
Name: TeslaModel Y Performance, DE Price: â‚¬63,667, Range: 415 km
Name: VolvoEX30 Single Motor ER, DE Price: â‚¬41,790, Range: 370 km
Name: BYDHAN, DE Price: â‚¬70,805, Range: 475 km
Name: Rolls-RoyceSpectre, DE Price: * â‚¬400,000, Range: 465 km
Name: RenaultMegane E-Tech EV60 220hp, DE Price: â‚¬46,600, Range: 380 km
Name: Smart#1, DE Price: â‚¬42,490, Range: 335 km
Name: DaciaSpring Electric 45, DE Price: â‚¬22,550, Range: 165 km
Name: BYDDOLPHIN 60.4 kWh, DE Price: â‚¬35,990, Range: 340 km
Name: TeslaModel S Plaid, DE Price: â‚¬110,970, Range: 560 km
Name: BYDSEAL 82.5 kWh RWD Design, DE Price: â‚¬47,578, Range: 500 km
Name: TeslaModel S Dual Motor, DE Price: â‚¬95,970, Range: 575 km
Name: BMWi5 eDrive40 Sedan, DE Price: â‚¬70,200, Range: 475 km
Name: BMWiX3, DE Price: â‚¬67,300, Range: 385 km
Name: AudiQ8 e-tron 55 quattro, DE Price: â‚¬85,300, Range: 505 km
Name: HyundaiIONIQ 6 Long Range AWD, DE Price: â‚¬61,100, Range: 440 km
Name: BYDTANG, DE Price: â‚¬71,400, Range: 360 km
Name: MGZS EV Long Range, DE Price: â‚¬37,990, Range: 370 km
Name: KiaEV6 Long Range 2WD, DE Price: â‚¬51,990, Range: 410 km
Name: HongqiE-HS9 99 kWh, DE Price: N/A, Range: 370 km
Name: ToyotabZ4X FWD, DE Price: â‚¬47,490, Range: 340 km
Name: HyundaiKona Electric 65 kWh, DE Price: â‚¬47,190, Range: 390 km
Name: TeslaModel Y, DE Price: â‚¬47,567, Range: 350 km
Name: Fiat500e Hatchback 42 kWh, DE Price: â‚¬34,990, Range: 235 km
Name: BMWiX xDrive50, DE Price: â‚¬100,100, Range: 505 km
Name: Peugeote-3008 73 kWh, DE Price: â‚¬48,650, Range: 385 km
Name: BMWi4 M50, DE Price: â‚¬70,800, Range: 450 km
Name: AudiQ4 e-tron 40, DE Price: N/A, Range: 405 km
Name: VolkswagenID.7 Pro, DE Price: â‚¬56,995, Range: 475 km
Name: BMWi7 xDrive60, DE Price: â‚¬139,900, Range: 510 km
Name: RenaultZoe ZE50 R110, DE Price: â‚¬36,840, Range: 315 km
Name: BYDDOLPHIN 44.9 kWh Active, DE Price: â‚¬29,990, Range: 255 km
Name: Peugeote-208, DE Price: â‚¬39,100, Range: 285 km
Name: CUPRABorn 150 kW - 58 kWh, DE Price: â‚¬39,370, Range: 350 km
Name: HyundaiIONIQ 5 Long Range 2WD, DE Price: â‚¬47,900, Range: 390 km
Name: MGMG4 Electric 51 kWh, DE Price: â‚¬34,990, Range: 300 km
Name: HyundaiIONIQ 6 Long Range 2WD, DE Price: â‚¬54,000, Range: 495 km
Name: SkodaEnyaq 85, DE Price: â‚¬48,900, Range: 455 km
Name: RenaultTwingo Electric, DE Price: â‚¬28,000, Range: 135 km
Name: MercedesEQA 250+, DE Price: N/A, Range: 420 km
Name: HyundaiIONIQ 5 N, DE Price: N/A, Range: 385 km
Name: KiaEV6 GT, DE Price: â‚¬72,990, Range: 360 km
Name: MiniCooper SE, DE Price: â‚¬35,700, Range: 180 km
Name: VolkswagenID.3 Pro, DE Price: â‚¬39,995, Range: 350 km
Name: Citroene-C4, DE Price: â‚¬36,040, Range: 290 km
Name: BMWi4 eDrive35, DE Price: â‚¬56,500, Range: 430 km
Name: KiaEV9 99.8 kWh AWD, DE Price: â‚¬76,490, Range: 425 km
Name: JeepAvenger Electric, DE Price: â‚¬37,000, Range: 310 km
Name: Audie-tron GT RS, DE Price: â‚¬146,050, Range: 405 km
Name: VolkswagenID. Buzz Pro, DE Price: â‚¬64,581, Range: 345 km
Name: Zeekr001 Performance AWD, DE Price: â‚¬63,970, Range: 505 km
Name: VolkswagenID.4 Pro, DE Price: â‚¬46,335, Range: 435 km
Name: Smart#1 Brabus, DE Price: â‚¬48,990, Range: 315 km
Name: Hondae:Ny1, DE Price: â‚¬47,590, Range: 335 km
Name: LucidAir Dream Edition R, DE Price: â‚¬218,000, Range: 685 km
Name: BMWiX1 eDrive20, DE Price: â‚¬47,900, Range: 390 km
Name: NissanLeaf, DE Price: â‚¬33,400, Range: 235 km
Name: OpelCorsa-e, DE Price: N/A, Range: 295 km
Name: OpelAstra Electric, DE Price: â‚¬41,990, Range: 305 km
Name: Peugeote-3008 98 kWh Long Range, DE Price: * â‚¬55,000, Range: 505 km
Name: NissanAriya 87kWh, DE Price: â‚¬58,990, Range: 450 km
Name: VolvoEX30 Single Motor, DE Price: â‚¬36,590, Range: 280 km
Name: MGMG4 Electric 77 kWh, DE Price: â‚¬45,990, Range: 425 km
Name: LotusEletre, DE Price: â‚¬95,990, Range: 495 km
Name: HyundaiIONIQ 5 Standard Range 2WD, DE Price: â‚¬43,900, Range: 295 km
Name: Smart#3, DE Price: â‚¬43,490, Range: 355 km
Name: CUPRABorn 170 kW - 77 kWh, DE Price: â‚¬46,450, Range: 450 km
Name: VolkswagenID.7 Pro S, DE Price: * â‚¬60,000, Range: 520 km
Name: FiskerOcean One, DE Price: â‚¬69,950, Range: 530 km
Name: Polestar2 Long Range Single Motor, DE Price: â‚¬54,475, Range: 470 km
Name: MGMG4 Electric XPOWER, DE Price: â‚¬46,990, Range: 320 km
Name: SubaruSolterra AWD, DE Price: â‚¬57,490, Range: 320 km
Name: MazdaMX-30, DE Price: â‚¬35,990, Range: 170 km
Name: OpelMokka-e 50 kWh, DE Price: â‚¬40,650, Range: 260 km
Name: Polestar4 Long Range Dual Motor, DE Price: * â‚¬65,000, Range: 465 km
Name: Zeekr001 Long Range RWD, DE Price: â‚¬60,970, Range: 530 km
Name: MGMG5 Electric Long Range, DE Price: â‚¬38,490, Range: 335 km
Name: RenaultZoe ZE50 R135, DE Price: â‚¬37,840, Range: 310 km
Name: TeslaModel X Dual Motor, DE Price: â‚¬100,970, Range: 475 km
Name: FiskerOcean Ultra, DE Price: â‚¬57,000, Range: 535 km
Name: LexusRZ 450e, DE Price: â‚¬68,000, Range: 320 km
Name: SkodaEnyaq Coupe 85, DE Price: â‚¬51,150, Range: 485 km
Name: MercedesEQB 350 4MATIC, DE Price: N/A, Range: 340 km
Name: MercedesEQB 250+, DE Price: â‚¬53,514, Range: 415 km
Name: MercedesEQS 450+, DE Price: â‚¬109,551, Range: 635 km
Name: HyundaiIONIQ 5 Long Range AWD, DE Price: â‚¬59,200, Range: 385 km
Name: VolvoEX30 Twin Motor Performance, DE Price: â‚¬48,490, Range: 360 km
Name: NIOET7 75 kWh, DE Price: â‚¬81,900, Range: 400 km
Name: BMWi5 M60 xDrive Sedan, DE Price: â‚¬99,500, Range: 425 km
Name: Peugeote-308, DE Price: â‚¬44,765, Range: 300 km
Name: AudiQ8 e-tron Sportback 55 quattro, DE Price: â‚¬87,550, Range: 525 km
Name: KiaEV6 Long Range AWD, DE Price: â‚¬55,980, Range: 400 km
Name: HyundaiKona Electric 39 kWh, DE Price: â‚¬36,400, Range: 245 km
Name: Smart#3 Brabus, DE Price: â‚¬50,990, Range: 330 km
Name: VolvoXC40 Recharge Single Motor ER, DE Price: â‚¬53,000, Range: 405 km
Name: HyundaiIONIQ 6 Standard Range 2WD, DE Price: â‚¬43,900, Range: 365 km
Name: Fiat600e, DE Price: â‚¬36,490, Range: 305 km
Name: BMWiX M60, DE Price: â‚¬136,100, Range: 485 km
Name: MaxusMIFA 9, DE Price: â‚¬68,990, Range: 365 km
Name: MGMarvel R, DE Price: â‚¬46,990, Range: 365 km
Name: VolvoXC40 Recharge Twin Motor, DE Price: â‚¬59,950, Range: 390 km
Name: MercedesEQB 300 4MATIC, DE Price: N/A, Range: 340 km
Name: VolkswagenID.5 Pro, DE Price: â‚¬48,970, Range: 455 km
Name: NIOET5 100 kWh, DE Price: â‚¬68,500, Range: 500 km
Name: Polestar4 Long Range Single Motor, DE Price: * â‚¬60,000, Range: 495 km
Name: Audie-tron GT quattro, DE Price: â‚¬106,050, Range: 420 km
Name: ZeekrX Privilege AWD, DE Price: â‚¬50,470, Range: 350 km
Name: Citroene-C4 X, DE Price: â‚¬37,540, Range: 285 km
Name: TeslaModel X Plaid, DE Price: â‚¬115,970, Range: 455 km
Name: ToyotabZ4X AWD, DE Price: â‚¬57,390, Range: 315 km
Name: MercedesEQE 350+, DE Price: N/A, Range: 530 km
Name: NissanLeaf e+, DE Price: â‚¬41,100, Range: 340 km
Name: MercedesEQA 250, DE Price: â‚¬50,777, Range: 405 km
Name: Peugeote-308 SW, DE Price: â‚¬45,765, Range: 300 km
Name: BMWiX2 xDrive30, DE Price: â‚¬56,500, Range: 380 km
Name: MGMarvel R Performance, DE Price: â‚¬50,990, Range: 350 km
Name: DaciaSpring Electric 65 Extreme, DE Price: â‚¬24,550, Range: 160 km
Name: KiaEV9 99.8 kWh RWD, DE Price: â‚¬72,490, Range: 450 km
Name: VolvoXC40 Recharge Single Motor, DE Price: â‚¬47,500, Range: 345 km
Name: MercedesEQV 300 Long, DE Price: â‚¬71,626, Range: 310 km
Name: MercedesEQS SUV 580 4MATIC, DE Price: â‚¬135,434, Range: 485 km
Name: Polestar2 Standard Range Single Motor, DE Price: â‚¬50,775, Range: 405 km
Name: XPENGG9 RWD Standard Range, DE Price: N/A, Range: 400 km
Name: XPENGP7 Wing Edition, DE Price: N/A, Range: 465 km
Name: VolkswagenID.3 Pro S - 4 Seats, DE Price: â‚¬47,595, Range: 455 km
Name: LucidAir Grand Touring, DE Price: â‚¬159,000, Range: 665 km
Name: AudiQ8 e-tron 50 quattro, DE Price: â‚¬74,400, Range: 425 km
Name: SkodaEnyaq 60, DE Price: â‚¬44,200, Range: 340 km
Name: SsangYongKorando e-Motion, DE Price: â‚¬40,490, Range: 290 km
Name: AudiQ4 e-tron 45, DE Price: â‚¬52,950, Range: 420 km
Name: HongqiE-HS9 84 kWh, DE Price: N/A, Range: 320 km
Name: RenaultMegane E-Tech EV40 130hp, DE Price: â‚¬42,000, Range: 260 km
Name: XPENGG9 RWD Long Range, DE Price: N/A, Range: 480 km
Name: MercedesEQS SUV 450+, DE Price: â‚¬110,801, Range: 500 km
Name: RenaultKangoo E-Tech Electric, DE Price: â‚¬39,300, Range: 220 km
Name: FiskerOcean Sport, DE Price: â‚¬41,560, Range: 380 km
Name: MGZS EV Standard Range, DE Price: â‚¬33,990, Range: 265 km
Name: KiaEV9 99.8 kWh AWD GT-Line, DE Price: â‚¬82,380, Range: 415 km
Name: RenaultMegane E-Tech EV60 130hp, DE Price: â‚¬47,000, Range: 380 km
Name: Peugeote-2008 54 kWh, DE Price: â‚¬40,050, Range: 300 km
Name: FordMustang Mach-E ER RWD, DE Price: â‚¬58,500, Range: 480 km
Name: AudiQ4 e-tron 50 quattro, DE Price: N/A, Range: 385 km
Name: VoyahFree 106 kWh, DE Price: N/A, Range: 480 km
Name: Polestar2 Long Range Dual Motor, DE Price: â‚¬58,775, Range: 450 km
Name: OpelCorsa Electric 51 kWh, DE Price: â‚¬38,045, Range: 315 km
Name: Polestar3 Long Range Dual motor, DE Price: â‚¬88,600, Range: 490 km
Name: CUPRATavascan VZ, DE Price: * â‚¬58,000, Range: 430 km
Name: MiniCooper SE, DE Price: â‚¬36,900, Range: 310 km
Name: SkodaEnyaq 85x, DE Price: â‚¬51,150, Range: 440 km
Name: VinFastVF 9 Extended Range, DE Price: â‚¬89,790, Range: 520 km
Name: VolkswagenID.4 Pure, DE Price: â‚¬40,335, Range: 285 km
Name: JaguarI-Pace EV400, DE Price: â‚¬92,400, Range: 380 km
Name: NissanAriya 63kWh, DE Price: â‚¬47,490, Range: 335 km
Name: MercedesEQE 300, DE Price: â‚¬67,187, Range: 525 km
Name: ORAFunky Cat 48 kWh, DE Price: â‚¬38,990, Range: 260 km
Name: LucidAir Dream Edition P, DE Price: â‚¬218,000, Range: 665 km
Name: NIOET7 100 kWh, DE Price: â‚¬90,900, Range: 505 km
Name: VolvoC40 Recharge Twin Motor, DE Price: â‚¬61,400, Range: 400 km
Name: VolvoC40 Recharge Single Motor ER, DE Price: â‚¬54,450, Range: 420 km
Name: FiskerOcean Extreme, DE Price: â‚¬69,950, Range: 530 km
Name: Citroene-C4 X 54 kWh, DE Price: â‚¬41,540, Range: 330 km
Name: MaseratiGranTurismo Folgore, DE Price: * â‚¬250,000, Range: 425 km
Name: MercedesEQE SUV 500 4MATIC, DE Price: â‚¬99,841, Range: 455 km
Name: OpelAstra Sports Tourer Electric, DE Price: â‚¬43,490, Range: 300 km
Name: VolvoEX90 Twin Motor, DE Price: â‚¬105,550, Range: 465 km
Name: NIOET5 Touring 100 kWh, DE Price: â‚¬68,500, Range: 485 km
Name: MercedesEQA 250+, DE Price: â‚¬52,205, Range: 430 km
Name: MercedesEQE SUV 350 4MATIC, DE Price: N/A, Range: 425 km
Name: LotusEletre R, DE Price: â‚¬150,990, Range: 455 km
Name: SkodaEnyaq Coupe RS, DE Price: â‚¬63,300, Range: 455 km
Name: NIOEL7 100 kWh, DE Price: â‚¬94,900, Range: 430 km
Name: KiaEV6 Standard Range 2WD, DE Price: â‚¬46,990, Range: 305 km
Name: BYDDOLPHIN 44.9 kWh Boost, DE Price: â‚¬32,740, Range: 255 km
Name: XPENGP7 RWD Long Range, DE Price: N/A, Range: 495 km
Name: XPENGG9 AWD Performance, DE Price: N/A, Range: 465 km
Name: BMWi7 eDrive50, DE Price: â‚¬115,700, Range: 520 km
Name: GenesisGV60 Premium, DE Price: N/A, Range: 390 km
Name: AudiSQ8 e-tron, DE Price: â‚¬95,800, Range: 455 km
Name: VolkswagenID.4 Pro 4MOTION, DE Price: â‚¬49,020, Range: 425 km
Name: HyundaiKona Electric 48 kWh, DE Price: â‚¬41,990, Range: 290 km
Name: Peugeote-208 51 kWh, DE Price: â‚¬36,775, Range: 310 km
Name: SkodaEnyaq Coupe 85x, DE Price: â‚¬53,400, Range: 470 km
Name: FordMustang Mach-E ER AWD, DE Price: â‚¬65,900, Range: 445 km
Name: BMWi7 M70 xDrive, DE Price: â‚¬181,800, Range: 490 km
Name: AudiQ4 e-tron 55 quattro, DE Price: â‚¬59,000, Range: 395 km
Name: MGMG5 Electric Standard Range, DE Price: â‚¬35,490, Range: 265 km
Name: PorscheTaycan GTS, DE Price: â‚¬139,906, Range: 450 km
Name: MiniCountryman E, DE Price: * â‚¬43,500, Range: 380 km
Name: OpelCorsa Electric 50 kWh, DE Price: â‚¬34,650, Range: 295 km
Name: MercedesEQS 580 4MATIC, DE Price: â‚¬141,705, Range: 590 km
Name: CUPRATavascan Endurance, DE Price: * â‚¬52,000, Range: 450 km
Name: Citroene-Berlingo M 50 kWh, DE Price: â‚¬37,790, Range: 205 km
Name: Kiae-Soul 64 kWh, DE Price: â‚¬46,950, Range: 370 km
Name: MercedesEQA 350 4MATIC, DE Price: N/A, Range: 350 km
Name: Peugeote-2008 50 kWh, DE Price: * â‚¬37,000, Range: 270 km
Name: Citroene-C4 54 kWh, DE Price: â‚¬41,540, Range: 330 km
Name: NIOEL6 100 kWh, DE Price: â‚¬74,500, Range: 440 km
Name: PorscheTaycan Plus, DE Price: â‚¬98,863, Range: 485 km
Name: AiwaysU5, DE Price: â‚¬39,563, Range: 315 km
Name: AudiQ4 Sportback e-tron 45, DE Price: â‚¬54,950, Range: 435 km
Name: PorscheTaycan Turbo S, DE Price: â‚¬197,740, Range: 430 km
Name: VolkswagenID.4 GTX, DE Price: â‚¬53,255, Range: 420 km
Name: MercedesEQA 300 4MATIC, DE Price: N/A, Range: 350 km
Name: LucidAir Touring, DE Price: â‚¬129,000, Range: 580 km
Name: Smart#1 Pro, DE Price: â‚¬37,490, Range: 255 km
Name: FordMustang Mach-E SR RWD, DE Price: â‚¬55,800, Range: 380 km
Name: MercedesEQS 450 4MATIC, DE Price: â‚¬113,359, Range: 610 km
Name: Seres3, DE Price: N/A, Range: 260 km
Name: AudiQ4 Sportback e-tron 40, DE Price: N/A, Range: 425 km
Name: Fiat500e Hatchback 24 kWh, DE Price: â‚¬30,990, Range: 135 km
Name: NIOET5 Touring 75 kWh, DE Price: â‚¬59,500, Range: 385 km
Name: e.Goe.wave X, DE Price: â‚¬24,990, Range: 150 km
Name: NissanAriya e-4ORCE 87kWh - 225 kW, DE Price: â‚¬61,990, Range: 405 km
Name: LucidAir Pure AWD, DE Price: â‚¬109,000, Range: 590 km
Name: MiniCooper E, DE Price: * â‚¬33,000, Range: 235 km
Name: Zeekr001 Privilege AWD, DE Price: â‚¬68,970, Range: 500 km
Name: MercedeseVito Tourer Long 90 kWh, DE Price: â‚¬64,248, Range: 310 km
Name: ORAFunky Cat 63 kWh, DE Price: â‚¬44,490, Range: 340 km
Name: MercedesEQE 350 4MATIC, DE Price: â‚¬74,149, Range: 510 km
Name: NIOET5 75 kWh, DE Price: â‚¬59,500, Range: 395 km
Name: Peugeote-208 50 kWh, DE Price: * â‚¬39,000, Range: 290 km
Name: MercedesEQE SUV 500 4MATIC, DE Price: N/A, Range: 435 km
Name: ZeekrX Long Range RWD, DE Price: â‚¬45,970, Range: 360 km
Name: MercedesEQE SUV 350+, DE Price: â‚¬86,811, Range: 475 km
Name: DS3 E-Tense, DE Price: â‚¬40,540, Range: 300 km
Name: MercedesEQS AMG 53 4MATIC+, DE Price: â‚¬155,009, Range: 535 km
Name: CUPRABorn 170 kW - 58 kWh, DE Price: â‚¬40,750, Range: 345 km
Name: NissanTownstar EV Passenger, DE Price: â‚¬39,990, Range: 225 km
Name: Polestar3 Long Range Performance, DE Price: â‚¬95,200, Range: 470 km
Name: VolvoC40 Recharge Single Motor, DE Price: â‚¬47,500, Range: 355 km
Name: MercedesEQB 350 4MATIC, DE Price: â‚¬58,197, Range: 345 km
Name: VolvoEX90 Twin Motor Performance, DE Price: â‚¬110,650, Range: 450 km
Name: FordMustang Mach-E GT, DE Price: â‚¬77,300, Range: 425 km
Name: Fiat500e 3+1 42 kWh, DE Price: â‚¬36,990, Range: 235 km
Name: Peugeote-3008 73 kWh Dual Motor, DE Price: * â‚¬50,000, Range: 370 km
Name: ElarisBEO 86 kWh, DE Price: â‚¬53,090, Range: 390 km
Name: VolkswagenID.5 GTX, DE Price: â‚¬56,455, Range: 430 km
Name: PorscheTaycan, DE Price: â‚¬93,139, Range: 420 km
Name: MaseratiGrecale Folgore, DE Price: N/A, Range: 405 km
Name: VolvoEX90 Single Motor, DE Price: N/A, Range: 460 km
Name: MercedesEQB 300 4MATIC, DE Price: â‚¬55,519, Range: 345 km
Name: ORAFunky Cat GT, DE Price: â‚¬49,490, Range: 330 km
Name: Polestar2 Long Range Performance, DE Price: â‚¬65,275, Range: 450 km
Name: GenesisG80 Electrified Luxury, DE Price: â‚¬69,200, Range: 440 km
Name: MercedesEQT 200 Standard, DE Price: â‚¬49,445, Range: 225 km
Name: XPENGP7 AWD Performance, DE Price: N/A, Range: 460 km
Name: AudiQ4 e-tron 45 quattro, DE Price: â‚¬54,950, Range: 395 km
Name: LexusUX 300e, DE Price: N/A, Range: 340 km
Name: AudiQ8 e-tron Sportback 50 quattro, DE Price: â‚¬76,650, Range: 445 km
Name: GenesisGV70 Electrified Sport, DE Price: â‚¬67,300, Range: 350 km
Name: MercedesEQS SUV 450 4MATIC, DE Price: â‚¬114,609, Range: 490 km
Name: MercedesEQE 350, DE Price: â‚¬70,995, Range: 515 km
Name: MiniCountryman SE ALL4, DE Price: * â‚¬50,000, Range: 370 km
Name: ToyotaProace City Verso Electric L2 50 kWh, DE Price: â‚¬40,150, Range: 205 km
Name: MercedesEQS SUV 500 4MATIC, DE Price: â‚¬124,545, Range: 490 km
Name: AudiQ4 Sportback e-tron 45 quattro, DE Price: â‚¬56,950, Range: 415 km
Name: MercedesEQE 500 4MATIC, DE Price: â‚¬88,215, Range: 505 km
Name: OpelVivaro-e Combi M 75 kWh, DE Price: â‚¬56,942, Range: 265 km
Name: AudiQ4 Sportback e-tron 55 quattro, DE Price: â‚¬61,000, Range: 415 km
Name: AudiQ4 Sportback e-tron 50 quattro, DE Price: N/A, Range: 400 km
Name: MercedesEQS 500 4MATIC, DE Price: â‚¬125,378, Range: 590 km
Name: HongqiE-HS9 120 kWh, DE Price: N/A, Range: 460 km
Name: FordMustang Mach-E SR AWD, DE Price: N/A, Range: 350 km
Name: Fiat500e 3+1 24 kWh, DE Price: N/A, Range: 135 km
Name: SkodaEnyaq Coupe 60, DE Price: N/A, Range: 355 km
Name: AudiSQ8 e-tron Sportback, DE Price: â‚¬98,050, Range: 480 km
Name: NissanAriya e-4ORCE 87kWh - 290 kW, DE Price: â‚¬71,490, Range: 405 km
Name: MercedesEQE SUV AMG 53 4MATIC+, DE Price: â‚¬139,438, Range: 410 km
Name: MercedesEQA 350 4MATIC, DE Price: â‚¬56,424, Range: 355 km
Name: PorscheTaycan 4S Plus, DE Price: â‚¬120,081, Range: 480 km
Name: ToyotaProace City Verso Electric L1 50 kWh, DE Price: â‚¬37,800, Range: 210 km
Name: SkodaEnyaq RS, DE Price: â‚¬61,050, Range: 435 km
Name: VinFastVF 8 Eco Extended Range, DE Price: â‚¬52,990, Range: 425 km
Name: MercedesEQE SUV 350 4MATIC, DE Price: â‚¬89,548, Range: 435 km
Name: Peugeote-Expert Combi Standard 75 kWh, DE Price: â‚¬57,940, Range: 265 km
Name: OpelCombo-e Life 50 kWh, DE Price: â‚¬43,050, Range: 205 km
Name: PorscheTaycan 4 Cross Turismo, DE Price: â‚¬103,254, Range: 440 km
Name: Fiat500e Cabrio 42 kWh, DE Price: â‚¬37,990, Range: 230 km
Name: MiniCooper SE Convertible, DE Price: N/A, Range: 165 km
Name: Smart#1 Pulse, DE Price: â‚¬46,490, Range: 320 km
Name: Peugeote-Rifter Long 50 kWh, DE Price: â‚¬42,440, Range: 200 km
Name: MercedesEQE SUV AMG 43 4MATIC, DE Price: â‚¬124,920, Range: 415 km
Name: PorscheTaycan GTS Sport Turismo, DE Price: â‚¬140,858, Range: 425 km
Name: NIOEL6 75 kWh, DE Price: â‚¬65,500, Range: 350 km
Name: Abarth500e Hatchback, DE Price: â‚¬37,990, Range: 225 km
Name: ToyotaPROACE Verso L 75 kWh, DE Price: â‚¬65,385, Range: 260 km
Name: ToyotaPROACE Verso M 75 kWh, DE Price: â‚¬64,530, Range: 265 km
Name: Citroene-Jumpy Combi M 75 kWh, DE Price: â‚¬57,940, Range: 265 km
Name: MercedesEQE SUV 300, DE Price: â‚¬83,479, Range: 450 km
Name: PorscheTaycan 4S, DE Price: â‚¬114,559, Range: 415 km
Name: AiwaysU6, DE Price: â‚¬47,588, Range: 350 km
Name: Kiae-Soul 39.2 kWh, DE Price: N/A, Range: 230 km
Name: MercedesEQE AMG 53 4MATIC+, DE Price: â‚¬110,706, Range: 465 km
Name: MercedeseVito Tourer Extra-Long 90 kWh, DE Price: â‚¬65,140, Range: 305 km
Name: OpelZafira-e Life L 75 kWh, DE Price: â‚¬70,075, Range: 260 km
Name: PorscheTaycan 4S Cross Turismo, DE Price: â‚¬119,914, Range: 440 km
Name: Abarth500e Convertible, DE Price: â‚¬40,990, Range: 225 km
Name: GenesisGV60 Sport, DE Price: â‚¬63,200, Range: 380 km
Name: PorscheTaycan Turbo, DE Price: â‚¬164,420, Range: 445 km
Name: MercedesEQA 300 4MATIC, DE Price: â‚¬53,520, Range: 355 km
Name: Peugeote-Rifter Standard 50 kWh, DE Price: â‚¬41,240, Range: 205 km

In [30]:
data_wrappers = pd.DataFrame(cars_list)
data_wrappers.head()

,name,de_price,uk_price,nl_price,acceleration_0-100km/h,top_speed,range,efficiency,fastcharge,towing_capacity(kg),availability
0,TeslaModel Y Long Range Dual Motor,"â‚¬59,017","Â£52,990","â‚¬54,993",5.0 sec,217 km/h,435 km,172 Wh/km,670 km/h,1600,Available to order since February 2022
1,BYDATTO 3,"â‚¬44,625","Â£37,195","â‚¬42,998",7.3 sec,160 km/h,330 km,183 Wh/km,370 km/h,,Available to order since August 2022
2,TeslaModel 3,"â‚¬46,220","Â£39,990","â‚¬43,993",6.1 sec,201 km/h,420 km,137 Wh/km,700 km/h,1000,Available to order since September 2023
3,TeslaModel 3 Long Range Dual Motor,"â‚¬55,220","Â£49,990","â‚¬51,993",4.4 sec,201 km/h,505 km,149 Wh/km,780 km/h,1000,Available to order since September 2023
4,TeslaModel Y,"â‚¬47,567","Â£44,990","â‚¬45,993",6.9 sec,217 km/h,350 km,164 Wh/km,580 km/h,1600,Available to order since November 2022

In [20]:
csv_file_path = r'C:\Users\photo\Desktop\Ironhack\projects\EV-Market-Dynamics\data\scraping\ev-database_prices22_scraping.csv'
data_wrappers.to_csv(csv_file_path, index=False)